tests:
    All pages are fast:
        path: /.*
        assertions:
            - main.wall_time < 50ms
            - main.io < 150ms
            - main.memory < 2Mb
            - metrics.sql.queries.count == 0
    All pages use no SQL queries:
        path: /.*
        assertions:
            - metrics.sql.queries.count == 0

scenarios:
    Home:
        - /
    Login:
        - /user
