tests:
    All pages are fast:
        path: /.*
        assertions:
            - main.wall_time < 50ms
            - main.io < 150ms
            - main.memory < 2Mb
    All pages process at least one SQL queries:
        path: /.*
        assertions:
            - metrics.sql.queries.count > 0

scenarios:
    Home:
        - /
    Login:
        - /user
